version: '2'

services:
  tourney.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - TournamentService=http://tourney.services.tournaments:5004
    ports:
      - "5001:5001"

  tourney.identity:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:5000"

  tourney.services.tournaments:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5004:5004"
    