version: '2'

services:
  tourney.web:
    image: tourney.web
    build:
      context: ./Tourney.Web
      dockerfile: Dockerfile
    depends_on:
      - tourney.services.participants

  tourney.identity:
    image: tourney.identity
    build:
      context: ./Tourney.Identity
      dockerfile: Dockerfile  

  tourney.services.participants:
    image: tourney.services.participants
    build:
      context: ./Tourney.Services.Participants
      dockerfile: Dockerfile
